# Set the base image to use
FROM gcc:latest
# Copy the C program into the container
COPY nflscores.c .
# Compile the C program
RUN gcc -o nflscores nflscores.c
# Set the command to run when the container starts
CMD ["./nflscores"]